language: java

addons:
  sonarcloud:
    organization: "sonarqube-123"
    token:
      secure: "GbVag+9OmGHLdeSACzXat3YIJ4ZAw3zZBlFIqK7BMOsHZnJ4xfu1OF8tSx2/RKDQz9rbYNe44v+eXkqtP5h/vqln4DXIfYdRidam59M6HQ/ROItyTAsQ2QoeX5VA4FVFAp34FU8vDAbkq8WW+q4cRP/FAMHOosNHD+iqE0uFaLVstY5Q8SOY2PX9vB5POCiyc1zKBkcs1bHFB8NYz/bhv9SqPMD79WRVolou4jFNXdUGFEcr2otgJIi3XV0kyNkqpcywlqM/6Muwh3G1g3jhw+gLciSC7eStrSRVWHjlAf2LSuvpKgMG4Ykpv89ibqTsMSkaLtBKC3Re8YKaj5oX1nq/k5DGX/4mk5eMouk+16MGPonn4Q/OJJCzR1UlqpvYtg4auH/QbF4OB1AtMJ+XNOwrEa3X/lBXjreeLv0U34wkQxh1diP8yC7yGvYX/nQS0ztHI7e6pvGp/H+dp+iFMHpMakxLG3OmJai3oNy6rTRn6H342q9CIdOGbCqd7Euz7myEEchRT0evcrTxUQy+kLGrhRxdlnFmh/Tr0TXkDs0iQah+5/uWeJ6gHHKoduaG0dnJtDFLy2kHT0uFDR/cnLqFGYke+9CAoV+uKWHGa60uCvBNWMamnZAEWKDatUyIcGBOHV2W5lYp05oS2WL31DZgWppnaiqMekDSlNKzBJo="
install: true

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=tousif-1_Juliet-Test-Case
