language: java

addons:
  sonarcloud:
    organization: "sonarqube-123"
    token:
      secure: "qlQxnM5antU/S1cL8fL61ObvJpU38D6Cnaf584q8rum+jl7gVmIqy8+0UqJX9veHpstl6JXvwIaZuLubE5LesWBLUN7qUqZv+6RGrJhszaO4b9mKBEx/qeNFC49te8FrVzFCWToalCqaMwIzkcV6cULz7rvsx8K6wyvnmhJQkZ2s5nOXlAD3xwEhnGs7JZcdrr5kCxXV0f5INhdXHLwJBKqP/e0LH5TMlIfF0WacDRHFoY8BXMLd+Nhao3M0CW8QOXQtFRcREyNnADgTgPrFUJUJa746fn8y6synNgXsJspgckj5K239yMiVWt0Hn2v6lyfv8mbKQR6s3jhav8k/SjVJcdmZ3EnmbKFtEffE+70MYdxneQzvqmEDREDq4YQrnlN5jZ8Cxn3NSbzRbbsF73N9d4yLyBcP6XWqJVdV43upsazAGPaq/v0/oWCFIL2F1h/g9r4kcBDPRWhkrXy+xUIQXNqmhhg9aMaa2QmeOxpg8AdVRqb8QOwLJ2Ag1jxv6TyWWQLhiMi4QFrnlT9OVgW+3e+gFdLZmOwDxBBIjGO5T0MlI1E16FT1lEn5o7wkpr5nHvNf/ile+gaeQFwU6fXXdE2f9hSQ/3cfK9cCTcYXQQ+sjMRJy0AAaVZWWFhNGC9Z5quOjZxKgt1vygBvL9LlIJhsmihdvl7zZ+hjzzQ="
install: true

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=bqcuong_Juliet-Test-Suite
